development:
  clients:
    default:
      database: <%= ENV['MONGO_NAME'] %>
      hosts:
        - <%= ENV['MONGO_HOST'] %>
      options:
        retry_writes: true
        max_pool_size: 5
  options: 
    raise_not_found_error: false
    
test:
  clients:
    default:
      database: movies_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 5
